### ISSUE TITLE
Installation issue on Raspberry Pi 4

### ISSUE THREAD

**Issue by tlhenvironment** [shikokuchuo/nanonext#1]
Hi, thanks for this package.

I want to install nanonext on a Raspberry Pi 4. I build R (v4.12) and libnng from source.
Installation from cran gives an error:

Thanks for any suggestions

```

* installing *source* package ‘nanonext’ ...
** package ‘nanonext’ successfully unpacked and MD5 sums checked
** using staged installation
Found libnng system installation...
** libs
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c core.c -o core.o
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c init.c -o init.o
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c opts.c -o opts.o
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c sockets.c -o sockets.o
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c utils.c -o utils.o
gcc -shared -L/opt/R/4.1.2/lib/R/lib -L/usr/local/lib -o nanonext.so core.o init.o opts.o sockets.o utils.o -L/usr/local/lib -lnng -L/opt/R/4.1.2/lib/R/lib -lR
installing to /home/XXX/R/armv7l-unknown-linux-gnueabihf-library/4.1/00LOCK-nanonext/00new/nanonext/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘nanonext’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/XXX/R/armv7l-unknown-linux-gnueabihf-library/4.1/00LOCK-nanonext/00new/nanonext/libs/nanonext.so':
  /home/XXX/R/armv7l-unknown-linux-gnueabihf-library/4.1/00LOCK-nanonext/00new/nanonext/libs/nanonext.so: undefined symbol: __atomic_fetch_sub_8
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/XXX/R/armv7l-unknown-linux-gnueabihf-library/4.1/nanonext’

The downloaded source packages are in
        ‘/tmp/RtmpT6GSCD/downloaded_packages’
Warning message:
In install.packages("nanonext") :
  installation of package ‘nanonext’ had non-zero exit status

```

**Comment by shikokuchuo** [comment]
It seems that perhaps you have a modified version of the NNG library for Raspberry Pi. This is a strange one as the CRAN tests pass on the MacOS Arm64 platform.

To get it working can you try the following:

1. Check you have cmake on your $PATH e.g. which cmake
2. Find where your system NNG header files are located, typically /usr/include/nng or /usr/local/include/nng
3. Temporarily rename the ‘nng’ folder something else
4. Try package installation again. As the configure script will fail to find the system installation, it will automatically download and build the latest NNG library (v1.5.2) as part of the package installation process and it should now succeed.

**Comment by shikokuchuo** [comment]
Alternatively, it has been suggested that you set
LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1
in your shell before before starting R.

The Python wrapper runs into this same issue: codypiersall/pynng#58

Hopefully this solves it for you!

**Comment by tlhenvironment** [comment]
> Alternatively, it has been suggested that you set LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 in your shell before before starting R.
> 
> The Python wrapper runs into this same issue: [codypiersall/pynng#58](https://github.com/codypiersall/pynng/issues/58)
> 
> Hopefully this solves it for you!

Thank you, it works if I run `export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1` before installation and before importing the package in R. If I don't set the variable before opening R but after successful installation, it gives an error similar to what the Python folks experience:

`> library(nanonext)
Error: package or namespace load failed for ‘nanonext’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/zickelei/R/armv7l-unknown-linux-gnueabihf-library/4.1/nanonext/libs/nanonext.so':
  /home/zickelei/R/armv7l-unknown-linux-gnueabihf-library/4.1/nanonext/libs/nanonext.so: undefined symbol: __atomic_fetch_sub_8
`

I might try it later again with the other way you suggested.

**Comment by tlhenvironment** [comment]
> Alternatively, it has been suggested that you set LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 in your shell before before starting R.
> 
> The Python wrapper runs into this same issue: [codypiersall/pynng#58](https://github.com/codypiersall/pynng/issues/58)
> 
> Hopefully this solves it for you!

I tried this, during the R package installation the script builds NNG, however then runs into the same problem:

`
Prior system libnng installation not found
[ 94%] Building C object CMakeFiles/nng.dir/src/supplemental/websocket/websocket.c.o
[ 96%] Linking C static library libnng.a
[ 96%] Built target nng
Scanning dependencies of target nngcat
[ 98%] Building C object src/tools/nngcat/CMakeFiles/nngcat.dir/nngcat.c.o
[100%] Linking C executable nngcat
[100%] Built target nngcat
** libs
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/tmp/Rtmps8mWMl/R.INSTALL3d555275e58b/nanonext/include  -fvisibility=hidden -fpic  -g -O2  -c core.c -o core.o
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/tmp/Rtmps8mWMl/R.INSTALL3d555275e58b/nanonext/include  -fvisibility=hidden -fpic  -g -O2  -c init.c -o init.o
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/tmp/Rtmps8mWMl/R.INSTALL3d555275e58b/nanonext/include  -fvisibility=hidden -fpic  -g -O2  -c opts.c -o opts.o
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/tmp/Rtmps8mWMl/R.INSTALL3d555275e58b/nanonext/include  -fvisibility=hidden -fpic  -g -O2  -c sockets.c -o sockets.o
gcc -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include  -I/tmp/Rtmps8mWMl/R.INSTALL3d555275e58b/nanonext/include  -fvisibility=hidden -fpic  -g -O2  -c utils.c -o utils.o
gcc -shared -L/opt/R/4.1.2/lib/R/lib -L/usr/local/lib -o nanonext.so core.o init.o opts.o sockets.o utils.o -L/tmp/Rtmps8mWMl/R.INSTALL3d555275e58b/nanonext/lib -lnng -L/opt/R/4.1.2/lib/R/lib -lR
installing to /home/zickelei/R/armv7l-unknown-linux-gnueabihf-library/4.1/00LOCK-nanonext/00new/nanonext/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘nanonext’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/XXX/R/armv7l-unknown-linux-gnueabihf-library/4.1/00LOCK-nanonext/00new/nanonext/libs/nanonext.so':
  /home/XXX/R/armv7l-unknown-linux-gnueabihf-library/4.1/00LOCK-nanonext/00new/nanonext/libs/nanonext.so: undefined symbol: __atomic_fetch_sub_8
`

It can still be installed with export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1, but needs to set the variable again  before each run of R.

**Comment by shikokuchuo** [comment]
Thanks for the detailed feedback.

I believe this is all down to a linker flag to libatomic missing at package installation time, for which I have now added a workaround.

Please can you try from within R:
1. `Sys.setenv(NANONEXT_ARM=1)` set environment variable
2. `install.packages("nanonext", repos = "https://shikokuchuo.r-universe.dev")` install the dev version from R-universe (works the same way as CRAN)

You would just need to set the environment variable for package installation, not at each runtime.

This should also work with your existing system installation of NNG.

**Comment by tlhenvironment** [comment]
Working, it builds nng and then completes package installation (Y)
Thx for quick fix!

**Comment by shikokuchuo** [comment]
Adding upstream ref: nanomsg/nng#1029
Non-trivial to automatically detect affected platforms so above fix + documentation to be added to a CRAN release >= 0.2.1

**Comment by shikokuchuo** [comment]
Automatic detection introduced by 95792cb - no more need to set an environment variable.
