### ISSUE TITLE
Release a version that uses dynamically linked NNG (which is also released)

### ISSUE THREAD

**Issue by brendanf** [shikokuchuo/nanonext#11]
As I mentioned in wlandau/crew#80, I am working on packaging nanonext for conda-forge.  The conda-forge policy is to prefer dynamically linked dependencies rather than bundled, and to *very* strongly prefer officially released versions.  It seems that the current release of nanonext depends on the unreleased v1.6.0 of NNG; while the unreleased version of nanonext has reduced this to [requiring only v1.5.1](https://github.com/shikokuchuo/nanonext/blob/052e7509d3c2c0f5b6572c8fa48218914eb9e231/configure#L131), which is released.  Would it be too much trouble for you to push a new release of nanonext which uses the released NNG?  Alternatively, do you have insight into when NNG 1.6.0 will be published?

**Comment by shikokuchuo** [comment]
Hi @brendanf luckily this has been on my mind as well, see the discussion here in case you haven't already: #10

The dev version is already compatible as you have noticed supporting NNG > 1.5.0, and I am planning a CRAN release by month-end.

**Comment by brendanf** [comment]
Ok great!  I didn't see that discussion yet, but it looks like all the necessary plans are in place.

**Comment by shikokuchuo** [comment]
@brendanf fyi nanonext 0.9.0 has now been released with system NNG > 1.5 support.
