### ISSUE TITLE
Trouble using until()

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/nanonext#18]
I am trying to use `mirai::nextget("cv")` in `controller$wait()` and `controller$map()` in `crew` in order to avoid the worst aspects of polling. But I am finding that `nanonext::until()` somehow decrements the condition variable. This leaves me with the unfortunate choice of (1) do not wait on `nextget("cv")` as I would like to do in #17, or (2) go back to the inefficient way of counting unresolved tasks (i.e. revert https://github.com/wlandau/crew/issues/131) because `cv_value(nextget("cv"))` can no longer be trusted to count resolved ones. Reprex:

```r
library(mirai)
library(nanonext)
url <- "ws://127.0.0.1:5700"
daemons(n = 1L, url = url)
launch_local(url = url)
cv <- nextget("cv")
cv_value(cv)
#> [1] 0
task <- mirai(TRUE, .signal = TRUE)
Sys.sleep(0.25)
cv_value(cv)
#> [1] 1
task <- mirai(Sys.sleep(1), .signal = TRUE)
until(cv, 2000)
cv_value(cv) # I would expect 2.
#> [1] 0
daemons(n = 0L)
```

**Comment by wlandau** [comment]
So it looks like `until()` decrements the cv even when it hits the timeout. So I can create an even smaller reprex:

``` r
library(nanonext)
#> Warning: package 'nanonext' was built under R version 4.3.1
cv <- cv()
cv_value(cv)
#> [1] 0
cv_signal(cv)
cv_signal(cv)
cv_value(cv)
#> [1] 2
until(cv, 10) # decrements the cv
cv_value(cv)
#> [1] 1
```

<sup>Created on 2023-10-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

@shikokuchuo, is the decrement always guaranteed to happen on every call to `until()`. If so, I *might* be able to work with this by defining my own version:

```r
crew_until <- function(condition, seconds_timeout) {
  on.exit(nanonext::cv_signal(condition))
  nanonext::until(cv = condition, msec = 1000 * seconds_timeout)
}
```

I will test this.

**Comment by wlandau** [comment]
Hmm..., it looks like `nanonext::until()` cannot decrement the cv any further if it is already 0, so then `cv_signal(condition)` would be incorrect. And `if (cv_value(condition) > 0L) cv_signal(condition)` is a race condition because what if a task completes after `if()` but before `cv_signal()`? The only other solution I can think of is to preemptively call `cv_signal()` a few thousand times before I submit any tasks at all, but that seems really messy and there is an edge case there.

So then would it be possible for `until()` to not signal the cv in the first place?

**Comment by wlandau** [comment]
Hmm... maybe I am misunderstanding the intended use cases of `wait()` and `until()`. I can see now that this is the intended behavior in the docs. In addition, I notice that `until()` only waits if `cv_value(cv)` is 0. Any positive value will not cause a wait:

```r
library(nanonext)
cv <- cv()
cv_signal(cv)
until(cv, 10000) # returns control instantly
```

This creates a challenge for me when using `mirai::nextget("cv")`. I would like to be able to wait on different kinds of conditions. Mainly:

* Wait until a `cv` value changes, regardless of its current value, without changing its value further.
* Wait until `cv_value(cv)` reaches a certain fixed number. `controller$wait()` and `controller$map()` could be simplified a lot with something like `nanonext::until(cv, msec, value_wake_up = 7L).

**Comment by wlandau** [comment]
And I think a manual `cv_decrement()` could also add a stronger meaning to `nextget("cv")`. Currently, `cv_value(nextget("cv"))` is the number of resolved tasks in the lifetime of the `crew` controller, regardless of whether they have been returned with `pop()`. If `nanonext` were to support a manual way to decrement a cv, then I could decrement it on each `pop()`. Now, the `cv` would indicate the number of resolved tasks currently available for collection, which is much more powerful and would allow me to make `controller$wait()` simpler and more efficient.

**Comment by shikokuchuo** [comment]
`until(cv, 1)` decrements your cv safely.

**Comment by shikokuchuo** [comment]
`until()` is correct and behaves as documented. If it is something else you are after please open a new feature request. It will not be implemented as a change to `until()`. Thanks.

**Comment by wlandau** [comment]
Sorry, that was a lot of thinking out loud on my part.

**Comment by shikokuchuo** [comment]
No worries! My comment just meant that any new functionality should belong in a new function. These synchronisation primitives are basic building blocks and it would not be right to amend them however convenient it may seem.
