### ISSUE TITLE
Performance of TLS encryption with a small number of small tasks

### ISSUE THREAD

**Issue by shikokuchuo** [shikokuchuo/nanonext#27]
### Discussed in https://github.com/shikokuchuo/nanonext/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **wlandau** January  2, 2024</sup>
Hi @shikokuchuo,

I hope you enjoyed your holidays!

Since `mirai` and `nanonext` are more robust than ever, I find myself thinking about performance, specifically when it comes to TLS encryption.

On my local Ubuntu machine, the following example with 100 tasks and TLS encryption takes almost 9 seconds to complete. I notice similar encryption-specific overhead when testing `crew.aws.batch` using real-life AWS Batch jobs.

```r
library(nanonext) # 0.11.0.9005
library(mirai) # 0.11.3.9003
daemons(n = 1L, dispatcher = TRUE, url = host_url(ws = TRUE, tls = TRUE))
url <- rownames(status()$daemons)
cv <- nextget("cv")
cv2 <- cv()
cv %~>% cv2
system(launch_remote(url = url), wait = FALSE)
msleep(5000)
n <- 1e2
start <- proc.time()["elapsed"]
tasks <- replicate(n, mirai(TRUE))
while (cv_value(cv) < n) {
  until_(cv2, 500)
}
lapply(tasks, unresolved)
elapsed <- unname(proc.time()["elapsed"] - start)
daemons(n = 0L)
print(elapsed)
```

When I turn off encryption, the same workload completes in under a tenth of a second.

```r
library(nanonext) # 0.11.0.9005
library(mirai) # 0.11.3.9003
daemons(n = 1L, dispatcher = TRUE)
url <- rownames(status()$daemons)
cv <- nextget("cv")
cv2 <- cv()
cv %~>% cv2
launch_local(url = url)
msleep(2000)
n <- 1e2
start <- proc.time()["elapsed"]
tasks <- replicate(n, mirai(TRUE))
while (cv_value(cv) < n) {
  until_(cv2, 500)
}
lapply(tasks, unresolved)
elapsed <- unname(proc.time()["elapsed"] - start)
daemons(n = 0L)
print(elapsed)
```

I know there is inevitable overhead from encryption/decryption and maybe extra steps in the handshake, but I would not have expected the slowdown to be quite this much, especially given how fast HTTP and HTTPS both load web pages.

You may already know where the bottleneck comes from, but I set up a quick profiling study anyway using `gperftools` and a few modifications in https://github.com/wlandau/nanonext/commit/dda175d86db9b2705937c2a23e743d0d8e6e70d0:

```r
library(nanonext) # my fork
library(mirai) # 0.11.3.9003
daemons(n = 1L, dispatcher = TRUE, url = host_url(ws = TRUE, tls = TRUE))
url <- rownames(status()$daemons)
cv <- nextget("cv")
cv2 <- cv()
cv %~>% cv2
system(launch_remote(url = url), wait = FALSE)
msleep(5000)
n <- 1e2
samples <- tempfile()
profiler_start(path = samples)
tasks <- replicate(n, mirai(TRUE))
while (cv_value(cv) < n) {
  until_(cv2, 500)
}
daemons(n = 0L)
profiler_stop()
proffer::serve_pprof(pprof = samples)
```

Unfortunately the flame graph is not useful. Looks like either a standard library function or system call is taking the most time, or the bottleneck comes from a non-interactive external process or thread.

![pprof](https://github.com/shikokuchuo/nanonext/assets/1580860/c6ae07fb-e1d7-4a5b-a4f7-e9508ee06f17)

</div>

**Comment by shikokuchuo** [comment]
I also don't think the difference should be so pronounced. I do indeed have some ideas and will look into this.

**Comment by wlandau** [comment]
Thanks for diagnosing and patching this so quickly! Tests on my company's SGE cluster run orders of magnitude faster now.

On Mac OS, however, I am seeing a dispatcher connection timeout every time. Any ideas?

``` r
library(nanonext) # 0.11.0.9006
library(mirai) # 0.11.3.9003
daemons(n = 1L, dispatcher = TRUE, url = host_url(ws = TRUE, tls = TRUE))
#> Error in daemons(n = 1L, dispatcher = TRUE, url = host_url(ws = TRUE, : initial sync with dispatcher timed out after 5s
```

<sup>Created on 2024-01-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31)
#>  os       macOS Sonoma 14.2.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Indiana/Indianapolis
#>  date     2024-01-03
#>  pandoc   3.1.2 @ /usr/local/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date (UTC) lib source
#>  cli           3.6.2       2023-12-11 [1] CRAN (R 4.3.1)
#>  digest        0.6.33      2023-07-07 [1] CRAN (R 4.3.0)
#>  evaluate      0.23        2023-11-01 [1] CRAN (R 4.3.1)
#>  fastmap       1.1.1       2023-02-24 [1] CRAN (R 4.3.0)
#>  fs            1.6.3       2023-07-20 [1] CRAN (R 4.3.0)
#>  glue          1.6.2       2022-02-24 [1] CRAN (R 4.3.0)
#>  htmltools     0.5.7       2023-11-03 [1] CRAN (R 4.3.1)
#>  knitr         1.45        2023-10-30 [1] CRAN (R 4.3.1)
#>  lifecycle     1.0.4       2023-11-07 [1] CRAN (R 4.3.1)
#>  magrittr      2.0.3       2022-03-30 [1] CRAN (R 4.3.0)
#>  mirai       * 0.11.3.9003 2024-01-02 [1] Github (shikokuchuo/mirai@5d9bd0d)
#>  nanonext    * 0.11.0.9006 2024-01-03 [1] Github (shikokuchuo/nanonext@5e984a9)
#>  purrr         1.0.2       2023-08-10 [1] CRAN (R 4.3.0)
#>  R.cache       0.16.0      2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3   1.8.2       2022-06-13 [1] CRAN (R 4.3.0)
#>  R.oo          1.25.0      2022-06-12 [1] CRAN (R 4.3.0)
#>  R.utils       2.12.3      2023-11-18 [1] CRAN (R 4.3.1)
#>  reprex        2.0.2       2022-08-17 [1] CRAN (R 4.3.0)
#>  rlang         1.1.2       2023-11-04 [1] CRAN (R 4.3.1)
#>  rmarkdown     2.25        2023-09-18 [1] CRAN (R 4.3.1)
#>  rstudioapi    0.15.0      2023-07-07 [1] CRAN (R 4.3.0)
#>  sessioninfo   1.2.2       2021-12-06 [1] CRAN (R 4.3.0)
#>  styler        1.10.2      2023-08-29 [1] CRAN (R 4.3.0)
#>  vctrs         0.6.5       2023-12-01 [1] CRAN (R 4.3.1)
#>  withr         2.5.2       2023-10-30 [1] CRAN (R 4.3.1)
#>  xfun          0.41        2023-11-01 [1] CRAN (R 4.3.1)
#>  yaml          2.3.8       2023-12-11 [1] CRAN (R 4.3.1)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by shikokuchuo** [comment]
That's completely coincidental - the output of `host_url(ws = TRUE, tls = TRUE)` is just giving you an invalid URL on that machine / network. If you want, you can raise a ticket at `mirai`. It's not related to this issue.

**Comment by shikokuchuo** [comment]
To be clear - the slow TLS was only an issue when building with the bundled libnng source - resulting from something I had inadvertently changed when trimming down the bundle. This has now been reverted - and is the default, not anything I added.

Conversely, you would also not come across this problem if linking against system libraries (or from building the full release tarball).

**Comment by wlandau** [comment]
> That's completely coincidental - the output of host_url(ws = TRUE, tls = TRUE) is just giving you an invalid URL on that machine / network. If you want, you can raise a ticket at mirai. It's not related to this issue.

Thanks for catching that. Indeed, it works when I set `url` to the more generic `"wss://127.0.0.1:0"`. This reminds me of the discussion in https://github.com/wlandau/crew.cluster/issues/1 on whether to use the host name or IP address. `crew` still uses the IPv4 (127.0.0.1 for the local machine, `getip::getip(type = "local")` for cloud and cluster launcher plugins).

**Comment by shikokuchuo** [comment]
https://github.com/wlandau/crew.cluster/issues/1! Looking back at the thread, I think I still favour an IP address where this works, particularly as our TLS implementation supports it. `mirai::host_url()` is only a convenience function and it is documented that the hostname is not guaranteed to work in all cases and to substitute the IP address where necessary.
