### ISSUE TITLE
nanonext is mutating the `NA` value shared across all R packages

### ISSUE THREAD

**Issue by lionel-** [shikokuchuo/nanonext#3]
Originally reported at https://github.com/r-lib/tidyselect/issues/265.

Expected behaviour:

```r
fn <- function() NA
fn <- compiler::cmpfun(fn)

attributes(fn())
#> NULL
```

Unexpected:

```r
library(nanonext)
s <- socket(dial = "inproc://nano")
r <- recv_aio(s)
r$data

attributes(fn())
#> $class
#> [1] "unresolvedValue"
```

This is a critical bug that breaks all sorts of things in other packages (for instance `devtools::load_all()` fails after that).

The problem occurs here: https://github.com/shikokuchuo/nanonext/blob/2dfe7e6dfbb7d49eebc49686a9f13268fd65e73c/src/aio.c#L276-L277. Before using mutating functions like `classgets()`, you should check that you own the object. `ScalarLogical()` returns shared objects. You can `duplicate()` before setting the class to fix this. Note that there is also a protection error, you should protect the result of `mkString()` before calling `classgets()` since the latter allocates, which triggers GC.

Unrelatedly, since S3 classes are not namespaced, you should in principle soft-namespace all S3 classes with your package name. For instance the `nanoContext` class belongs in principle to the `nano` package. A proper class name for your package would be `nanonextContext`.

**Comment by shikokuchuo** [comment]
Thanks @lionel- this is much appreciated, and fixed now in 5575414.

I understand `mkString()` allocates, which is why I have protected `res` and `classgets()` protects its arguments unless I am mistaken. I do run the package through rchk, although that is of course not failsafe either...

**Comment by lionel-** [comment]
oh yes you're right it does protect its arguments.

**Comment by lionel-** [comment]
and thanks for the quick fix!
