### ISSUE TITLE
Update request from CRAN

### ISSUE THREAD

**Issue by shikokuchuo** [shikokuchuo/nanonext#35]
> From: Kurt Hornik
Subject: CRAN package nanonext
Cc: CRAN@R-project.org
Date: Sun, 23 Jun 2024 19:24:05 +0200
>
> Dear maintainer,
>
 >Please see the problems shown on
[<https://cran.r-project.org/web/checks/check_results_nanonext.html>](https://cran.r-project.org/web/checks/check_results_nanonext.html).
>
> Please correct before 2024-07-07 to safely retain your package on CRAN.
>
> Best,
-k

**Comment by HenrikBengtsson** [comment]
Is this related to:

```
Error in request(.context(sock), data = data, send_mode = 1L, recv_mode = 1L,  : 
      R_ExternalPtrTag: argument of type NILSXP is not an external pointer
```

in the [CRAN R-devel checks](https://cran.r-project.org/web/checks/check_results_mirai.html)?  I also get these errors over at [**future.mirai**](https://github.com/HenrikBengtsson/future.mirai/issues/14), with a noticed from CRAN to fix it before 2024-07-07.

**Comment by shikokuchuo** [comment]
This is the same and due to Luke fiddling with the C API here: https://github.com/wch/r-source/commit/b7b2766f0dba85648ea5be8c268e923e4ec47ae9.

**Comment by shikokuchuo** [comment]
This is not something that affects the current dev version of `nanonext` so I guess I'll just have to submit that to CRAN. This should automatically solve your issues @HenrikBengtsson.

**Comment by shikokuchuo** [comment]
An updated version of `nanonext` has been submitted to CRAN. Once accepted, this will automatically fix similar errors experienced by downstream packages. There is no need to perform any action on this issue, please await further updates here. Thanks.

**Comment by shikokuchuo** [comment]
nanonext 1.1.1 has been accepted onto CRAN and is propagating to all the test platforms. It may then take a few days for downstream package tests to re-run, but should be automatic.

**Comment by shikokuchuo** [comment]
Related downstream check errors have now all been cured.
